name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  # Xiaomi
  build-pocom3-a13:
    name: "Build POCO M3 (A13)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-pocom3-a13.yml
    secrets: inherit
  
